### ISSUE TITLE
Emulating an In-Memory store using SQLite

### ISSUE THREAD

**Issue by k00ni** [semsol/arc2#105]
@semsol: I was thinking about the idea to "copy" your SPARQL => SQL engine to SQLite and emulate an In-Memory store, because SQLite can run in memory and is basically always available. 

Do you have any major concerns or might this worth a shot?

**Comment by semsol** [comment]
It's the same approach I would take for in-memory sparqling. I've actually started work on a new (property) graph store that will use SQLite quite a bit. It's a a very powerful DB engine. It needs a slightly different approach for partitioning larger datasets, but if I ever get to ARC3, it would also be based on SQLite instead of MySQL.

**Comment by k00ni** [comment]
Could you provide some more information about your work? That would be great.

Also, larger datasets and SQLite seems very contrary. Do you think of a "group" of SQLite files or some kind of in-memory+offline database?

**Comment by semsol** [comment]
yes, very very many sqlite files, dynamically combined via SQLite's ATTACH option.
